### PR TITLE
set user_id

### PR DESCRIPTION
**Pull request by pollett**
Untested and conceptual, but this should do it @jaredsilver 

I'll run it by @ludov04 tomorrow

I can't think of any privacy issues etc by putting the user id in a cookie? It's not really any different to it being put in the page and sent to snowplow/google?

### CODE REVIEW

**Review by jaredsilver — APPROVED** [review]
I like it! Thanks, Michael!

**Comment by pollett** [comment]
Also, @jaredsilver, given this will be set on every page request to an auth'd page, can we set the max-age shorter? It get's a little scattered around domains at the moment (i.e. www.datacamp, campus.datacamp, teach.datacamp etc), and I can't think of a nice way to get the base domain at the moment.  
Might be a bit confusing for 5mins after logout

**Comment by jaredsilver** [comment]
Yes, that's fine -- it can even be 1 second theoretically.

**Comment by pollett** [comment]
@jaredsilver is this still useful? If so we can test and deploy

**Comment by jaredsilver** [comment]
@pollett Yes! This would be wonderful. Let's go for it!

**Comment by jaredsilver** [comment]
@pollett Any updates on this one?

**Comment by pollett** [comment]
@jaredsilver this is now in prod

**Pull request merged**
